name: Close Production Pull Request

# only trigger on pull request closed events
on: push
jobs:
  merge_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Package
        uses: ./.github/actions/build-package
        with:
          DEV_HUB_AUTH_URL: ${{ secrets.DEV_HUB_AUTH_URL }}
          PACKAGE: 0Hoak0000000CXRCA2
